# -*- coding: utf-8 -*-


# This file was *autogenerated* from the file /Users/thomashoffbauer/Desktop/Mathematische Texte/masse_konstitution_test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_30 = Integer(30); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_113160 = Integer(113160); _sage_const_60 = Integer(60)#!/usr/bin/env sage
# Masse-Konstitution: Π_Γ-Zerlegung, ED-Sichtbarkeit, Hurwitz-Fluktuation (I_5/I_7)
# Start: ./run_masse_test.sh  oder  sage masse_konstitution_test.sage

import os

from sage.all import QQ, ZZ, is_prime

_here = os.path.dirname(os.path.abspath(__file__)) if "__file__" in dir() else os.getcwd()
globals()["_skip_hurwitz_main"] = True
load(os.path.join(_here, "rundweg_hurwitz_resonanz.sage"))


def pi_gamma_q(q):
    """q_sicht = Π_Γ(q) über (e,a,b,c)-Koordinaten."""
    return q_from_eabc(*kollaps_eabc(*eabc_from_q(q)))


def decompose_q(q):
    q_sicht = pi_gamma_q(q)
    return q_sicht, q - q_sicht


def ed_sichtbar(q_sicht):
    return not q_sicht.is_zero()


def _reachability(adj):
    """Transitive Hülle auf {E,A,B,C}."""
    nodes = ("E", "A", "B", "C")
    reach = {a: {b for b in nodes if b in adj.get(a, set())} for a in nodes}
    for k in nodes:
        reach[k].add(k)
    changed = True
    while changed:
        changed = False
        for a in nodes:
            for b in list(reach[a]):
                for c in reach.get(b, set()):
                    if c not in reach[a]:
                        reach[a].add(c)
                        changed = True
    return reach


def graph_zweiweg_flag(transitions_rows):
    """
    Operatives Zweiweg-Kriterium: ∃ X≠Y mit Pfad X→Y und Y→X in der aktiven Kantengraphik.
    """
    if not transitions_rows:
        return None
    adj = {n: set() for n in ("E", "A", "B", "C")}
    for row in transitions_rows:
        a, b = row.get("label_from"), row.get("label_to")
        if a in adj and b in adj:
            adj[a].add(b)
    reach = _reachability(adj)
    for x in adj:
        for y in adj:
            if x == y:
                continue
            if y in reach[x] and x in reach[y]:
                return True
    return False


def h32_aggregate_for_M(M):
    occupied = [r for r in H32 if is_prime(M + r)]
    counts = {"E": _sage_const_0 , "A": _sage_const_0 , "B": _sage_const_0 , "C": _sage_const_0 }
    for r in occupied:
        fl = eabc_class_mod12(M + r)
        if fl in counts:
            counts[fl] += _sage_const_1 
    q = quaternion_from_flavor_counts(counts)
    return q, counts, len(occupied)


def zeitwuerfel_aggregates_for_M(M, *, data_dir=None):
    if data_dir is None:
        data_dir = _here
    ev_path = os.path.join(data_dir, "bamberger_zeitwuerfel_active_events.csv")
    tr_path = os.path.join(data_dir, "bamberger_zeitwuerfel_active_transitions.csv")
    events = _read_csv_rows(ev_path)
    transitions = _read_csv_rows(tr_path)
    if events is None:
        return {
            "loaded": False,
            "events_path": ev_path,
            "transitions": None,
        }

    occupied = [r for r in H32 if is_prime(M + r)]
    mod30_slots = {}
    for r in occupied:
        key = int(r) % _sage_const_30 
        mod30_slots.setdefault(key, []).append(r)

    active_labels = []
    phase_labels = []
    for row in events:
        lab = row.get("label", "")
        if lab not in ("E", "A", "B", "C"):
            continue
        active_labels.append(lab)
        nk = row.get("n_k")
        if nk is None:
            continue
        rhat = int(float(nk)) % _sage_const_30 
        if rhat not in mod30_slots:
            continue
        phase_labels.append(lab)

    counts_all = _counts_from_labels(active_labels)
    counts_phase = _counts_from_labels(phase_labels)
    q_all = quaternion_from_flavor_counts(counts_all)
    q_phase = quaternion_from_flavor_counts(counts_phase) if phase_labels else None
    zweiweg = graph_zweiweg_flag(transitions)

    return {
        "loaded": True,
        "events_path": ev_path,
        "transitions": transitions,
        "counts_all": counts_all,
        "counts_phase": counts_phase,
        "q_all": q_all,
        "q_phase": q_phase,
        "n_active": len(active_labels),
        "n_phase": len(phase_labels),
        "zweiweg": zweiweg,
    }


def masse_kandidat_ok(q_sicht, *, zweiweg_flag=None):
    if not ed_sichtbar(q_sicht):
        return False, "q_sicht = 0 (nur Fluktuation / V_{λ=0})"
    n = q_norm(q_sicht)
    if n < _sage_const_1 :
        return False, f"N(q_sicht) = {n} < 1"
    msg = f"ED-sichtbar, N(q_sicht) = {n}"
    if zweiweg_flag is not None:
        msg += f", Zweiweg (Graph) = {'ja' if zweiweg_flag else 'nein'}"
    return True, msg


def analyse_masse_konstitution(q, label, *, zweiweg_flag=None, primes=None):
    if primes is None:
        primes = [_sage_const_5 , _sage_const_7 ]
    q_sicht, q_fluk = decompose_q(q)
    ok, grund = masse_kandidat_ok(q_sicht, zweiweg_flag=zweiweg_flag)

    print(f"\n=== Masse-Konstitution: {label} ===")
    print(f"  q       = {eabc_from_q(q)},  N(q)       = {q_norm(q)}")
    print(f"  q_sicht = {eabc_from_q(q_sicht)},  N(q_sicht) = {q_norm(q_sicht)}")
    print(f"  q_fluk  = {eabc_from_q(q_fluk)},  N(q_fluk)  = {q_norm(q_fluk)}")
    print(f"  ED-sichtbar (Π_Γ): {'ja' if ed_sichtbar(q_sicht) else 'nein'}")
    print(f"  Masse-Kandidat:    {'JA' if ok else 'NEIN'}  ({grund})")

    if not q_fluk.is_zero():
        resonanz_report(q_fluk, f"q_fluk — {label}", primes)
    else:
        print(f"\n--- q_fluk ({label}): trivial (0) — kein Fluktuations-Resonanztest ---")

    return {
        "label": label,
        "q": eabc_from_q(q),
        "q_sicht": eabc_from_q(q_sicht),
        "q_fluk": eabc_from_q(q_fluk),
        "N_sicht": q_norm(q_sicht),
        "N_fluk": q_norm(q_fluk),
        "ed_sichtbar": ed_sichtbar(q_sicht),
        "masse_kandidat": ok,
        "grund": grund,
        "zweiweg": zweiweg_flag,
        "I5_fluk": in_linksideal(q_fluk, primquaternionen()[_sage_const_5 ])[_sage_const_0 ] if not q_fluk.is_zero() else False,
        "I7_fluk": in_linksideal(q_fluk, primquaternionen()[_sage_const_7 ])[_sage_const_0 ] if not q_fluk.is_zero() else False,
    }


def main():
    M = _sage_const_113160 
    print("=== MASSE-KONSTITUTION-TEST (Π_Γ, Hurwitz I_5/I_7) ===")
    print(f"M = {M}  (H32-Phasenzentrum / Ptolemäus-Kontext)")
    print()

    results = []

    q_h32, counts_h32, n_occ = h32_aggregate_for_M(M)
    print(f"H32: {n_occ} belegte Slots, EABC-Zähler {counts_h32}")
    results.append(
        analyse_masse_konstitution(
            q_h32,
            f"H32-Aggregat M={M}",
            zweiweg_flag=None,
        )
    )

    zw = zeitwuerfel_aggregates_for_M(M)
    if not zw.get("loaded"):
        print(f"\nZeitwürfel: keine CSV ({zw.get('events_path')}) — nur H32 getestet.")
        print("  Optional: python3 'Jitter Zeit.py'")
    else:
        print(
            f"\nZeitwürfel geladen: {zw['n_active']} aktive Ereignisse, "
            f"{zw['n_phase']} phasengekoppelt (Mod 30)"
        )
        zweiweg = zw.get("zweiweg")
        print(f"  Zweiweg-Flag (bidirektionale EABC-Pfade in Übergängen): {zweiweg}")

        results.append(
            analyse_masse_konstitution(
                zw["q_all"],
                f"Zeitwürfel-Aggregat (aktiv, M={M})",
                zweiweg_flag=zweiweg,
            )
        )
        if zw.get("q_phase") is not None and zw["n_phase"] > _sage_const_0 :
            results.append(
                analyse_masse_konstitution(
                    zw["q_phase"],
                    f"Zeitwürfel phasengekoppelt (M={M})",
                    zweiweg_flag=zweiweg,
                )
            )

    kandidaten = [r for r in results if r["masse_kandidat"]]
    print("\n" + "=" * _sage_const_60 )
    print("ZUSAMMENFASSUNG M=113160")
    print(f"  Quellen getestet: {len(results)}")
    print(f"  Masse-Kandidaten (q_sicht ≠ 0, N ≥ 1): {len(kandidaten)}")
    for r in kandidaten:
        print(f"    • {r['label']}: q_sicht={r['q_sicht']}, N={r['N_sicht']}")
    if not kandidaten:
        print("    (keiner — prüfe Π_Γ-Anteil und Aggregat-Zähler)")
    any_fluk_res = any(r["I5_fluk"] or r["I7_fluk"] for r in results)
    print(f"  Fluktuation q_fluk in I_5 ∪ I_7: {'ja' if any_fluk_res else 'nein'}")
    print("=" * _sage_const_60 )
    print(">>> masse_konstitution_test: Ende")


if __name__ == "__main__":
    main()

